# -*- coding: utf-8 -*-
"""data_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjjuZ_Fq2mfjdqh2mKkioam7LdncqCFq

Libraries
"""

import os
import kagglehub
import pandas as pd

"""Extract Data"""

def Path(kaggle_path):
  # Download latest version of dataset from Kaggle
  path = kagglehub.dataset_download(kaggle_path)
  # Print directory path
  print("Path to dataset files:", path)
  return path

def extract_file(path):
  # List contents of the directory
  try:
    files = []
    if os.path.exists(path):
      for file in os.listdir(path):
        if file.endswith('.csv'):
          files.append(os.path.join(path, file))
      print(f'Contents of directory: {files}')
      return files
    else:
      print('Not a directory.')
  except Exception as e:
    print(f'Exception: {e}')

def extract_data():
  # hardcoded
  kaggle_path = "adilshamim8/netflix-stock-price-history"
  # Get directory path
  path = Path(kaggle_path)
  # Get files in directory
  files = extract_file(path)
  # Extract data from path
  df = pd.read_csv(files[0])
  return df

# Testing
def main():
  df = extract_data()
  print(df.head(10))

if __name__ == '__main__':
  main()